DCH/Models/Event.cs
using System.ComponentModel.DataAnnotations;

namespace DCH.Models
{
    public class Event
    {
        public int Id { get; set; }
        public int ClickCount { get; set; } = 0;
        public int MaxCount { get; set; }
        public int ReverseCount { get; set; }
        public List<int> RegisteredActors { get; set; } = new List<int>();

        [Required(ErrorMessage = "Indtsast venligst navn på event"),
            MinLength(1), MaxLength(40),]
        public string Name { get; set; }

        [Required(ErrorMessage = "Beskrivelse af dit event er nødvendigt"),
            MinLength(1), MaxLength(200),]
        public string Description { get; set; }

        [Required(ErrorMessage = "Bynavn er påkrævet"), MinLength(1), MaxLength(20),]
        public string City { get; set; }

        [Required(ErrorMessage = "DateTime is required")] //Dette er en indbygget valideringsattribut i .NET, der angiver, at DateTime-egenskaben er påkrævet, hvilket betyder, at den ikke kan være null. Hvis værdien er null, eller hvis feltet er tomt, vil denne valideringsattribut tilføje fejlmeddelelsen "DateTime is required"
        [CustomDateValidation(ErrorMessage = "Event datoen skal være fra d.d eller i fremtiden.")] // Dette er en brugerdefineret valideringsattribut, som du har oprettet, der specificerer yderligere valideringsregler for DateTime-egenskaben. I dette tilfælde kræver attributten, at DateTime skal være i dag eller i fremtiden. Hvis DateTime-værdien er i fortiden, returnerer denne valideringsattribut en fejlmeddelelse "Event datoen skal være fra d.d eller i fremtiden."
        public DateTime DateTime { get; set; } // Dette er en propertie til DateTime 

        public class CustomDateValidationAttribute : ValidationAttribute // CustomDateValidationAttribute er brugerdefineret valideringsattribut kaldet og ValidationAttribute er en indbygget attribut som bliver udvidet
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                if (value is DateTime dateValue)
                {
                    if (dateValue < DateTime.Today)
                    {
                        return new ValidationResult(ErrorMessage ?? "Event datoen skal være fra d.d eller i fremtiden.");
                    }
                }
                return ValidationResult.Success;
            }
        }
    }
}

DCH/Pages/Events/CreateEvent.cshtml.cs
using DCH.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DCH.Interfaces;

namespace DCH.Pages.Events
{
    public class CreateEventModel : PageModel
    {
        private IEventRepository catalog;
        [BindProperty]
        public Event Event { get; set; }

        public CreateEventModel(IEventRepository cat) 
        {
            catalog = cat;
        }
        

        public IActionResult OnGet(int id)
        {
            Event = new Event();
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (Event.Id == 0)
            {
                catalog.AddEvent(Event);
            }
            return RedirectToPage("GetAllEvents");
        }
    }
}

DCH/Pages/Events/DeleteEvent.cshtml.cs
using DCH.Interfaces;
using DCH.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DCH.Pages.Events
{
    public class DeleteEventModel : PageModel
    {
        [BindProperty]
        public Event Event { get; set; }

        private IEventRepository catalog;

        public DeleteEventModel(IEventRepository eventRepository)
        {
            catalog = eventRepository;
        }

        public IActionResult OnGet(int id)
            {
                Event = catalog.GetEvents(id);
                return Page();
            }

            public IActionResult OnPost(int id)
            {
                catalog.DeleteEvent(id);
                return RedirectToPage("GetAllEvents");
            }
    }


}
    

DCH/Pages/Events/GetAllEvents.cshtml.cs
using DCH.Interfaces;
using DCH.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DCH.Pages.Events
{
    public class GetAllEventsModel : PageModel
    {
        private IEventRepository catalog;
        public Dictionary<int, Event> FilteredEvents { get; set; }

        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }

        public GetAllEventsModel(IEventRepository cat)
        {
            catalog = cat;
        }
        public Dictionary<int, Event> Events { get; private set; }
        public IActionResult OnGet()
        {
            Events = catalog.AllEvents();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Events = catalog.FilterEvents(FilterCriteria);
            }
            return Page();
        }
    }
}

DCH/Pages/Events/ReadOnlyEvents.cshtml.cs
using DCH.Interfaces;
using DCH.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Runtime.CompilerServices;

namespace DCH.Pages.Events
{
    public class ReadOnlyEventsModel : PageModel
    {
        private IEventRepository catalog;
        public int ClickCount { get; set; } = 0;
        public Dictionary<int, Event> FilteredEvents { get; set; }
        public Actor Actor { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Source { get; set; }

        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }

        public ReadOnlyEventsModel(IEventRepository cat)
        {
                catalog = cat;
        }
        public Dictionary<int, Event> Events { get; private set; }
        public IActionResult OnGet()
        {
            Events = catalog.AllEvents();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Events = catalog.FilterEvents(FilterCriteria);
            }
            return Page();
        }

        public IActionResult OnPostRegister(int eventId)
        {
            var actorId = GetActorId();

            Events = catalog.AllEvents();
            if (Events.ContainsKey(eventId))
            {
                var eventItem = Events[eventId];
                if (Events[eventId].ClickCount <= Events[eventId].MaxCount - 1 && !eventItem.RegisteredActors.Contains(actorId))
                {
                    Events[eventId].ClickCount++;
                    eventItem.RegisteredActors.Add(actorId);
                    catalog.UpdateEvent(Events[eventId]);
                }                          
            }

            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Events = catalog.FilterEvents(FilterCriteria);
            }
            return Page();
        }
        public IActionResult OnPostUndoRegister(int eventId)
        {
            var actorId = GetActorId();

            Events = catalog.AllEvents();
            if (Events.ContainsKey(eventId))
            {
                var eventItem = Events[eventId];

                if (Events[eventId].ClickCount <= Events[eventId].MaxCount - 1 && eventItem.RegisteredActors.Contains(actorId))
                {
                    Events[eventId].ClickCount--;
                    eventItem.RegisteredActors.Remove(actorId);
                    catalog.UpdateEvent(Events[eventId]);
                }
            }

            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Events = catalog.FilterEvents(FilterCriteria);
            }
            return Page();
        }

        private int GetActorId() 
        {
            //Findes the logged in json actorId
            var actorJson = HttpContext.Session.GetString("LoggedInActor");

            if (actorJson != null)
            {
                //if actorJson is not null --> deserializing the specifik actor from json
                var loggedInActor = JsonConvert.DeserializeObject<Actor>(actorJson);
                return loggedInActor.Id;
            }
            return -1;
        }
    }
}

DCH/Pages/Events/UpdateEvent.cshtml.cs
using DCH.Interfaces;
using DCH.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DCH.Pages.Events
{
    public class UpdateEventModel : PageModel
    {
        private IEventRepository catalog;

        [BindProperty]
        public Event Event { get; set; }

        public UpdateEventModel(IEventRepository cat) 
        {
            catalog = cat;
        }

        public void OnGet(int id)
        {
            Event = catalog.GetEvents(id);
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            catalog.UpdateEvent(Event);
            return RedirectToPage("GetAllEvents");
        }
    }
}

DCH/Pages/Events/CreateEvent.cshtml
@page
@model DCH.Pages.Events.CreateEventModel
@{
    ViewData["Title"] = "Create Event";
}

<h1>Create Event</h1>

<form method="post">

    <div class="form-group">
        <input asp-for="@Model.Event.Id" class="form-control" type="hidden"/>
        <span asp-validation-for="@Model.Event.Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.Name" class="control-label">Event Navn (Må højst indholde 40 tegn)</label>
        <input asp-for="@Model.Event.Name" class="form-control" />
        <span asp-validation-for="@Model.Event.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.Description" class="control-label">Beskrivelse (Må højst indholde 200 tegn) </label>
        <input asp-for="@Model.Event.Description" class="form-control" />
        <span asp-validation-for="@Model.Event.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.City" class="control-label">By (Må højst indholde 20 tegn)</label>
        <input asp-for="@Model.Event.City" class="form-control" />
        <span asp-validation-for="@Model.Event.City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.MaxCount" class="control-label">Maks antal deltagere</label>
        <input asp-for="@Model.Event.MaxCount" class="form-control" />
        <span asp-validation-for="@Model.Event.MaxCount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.DateTime" class="control-label">Dato og klokkeslæt</label>
        <input asp-for="@Model.Event.DateTime" value="@Model.Event.DateTime.ToString("DD-MM-YYYY")" class="form-control" />
        <span asp-validation-for="@Model.Event.DateTime" class="text-danger"></span>
    </div>

    <div class="form-group button-container">
        <input type="submit" value="Opret" class="btn btn-primary large-btn" />
        <a asp-page="/Events/GetAllEvents" class="btn btn-secondary large-btn">Tilbage til event listen</a>
    </div>
</form>

DCH/Pages/Events/DeleteEvent.cshtml
@page
@model DCH.Pages.Events.DeleteEventModel
@{
    ViewData["Title"] = "DeleteEvent";
}

<h3>Er du sikker på at du vil slette dette event?</h3>
<div>
    <form method="post">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Event.Id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Event.Id)
            </dd>
            <dt class="col-sm-2">
                @* @Html.DisplayNameFor(model => model.Event.Name) *@
                <p>Navn</p>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Event.Name)
            </dd>
            <dt class="col-sm-2">
                @* @Html.DisplayNameFor(model => model.Event.Description) *@
                <p>Beskrivelse</p>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Event.Description)
            </dd>
            <dt class="col-sm-2">
                @* @Html.DisplayNameFor(model => model.Event.City) *@
                <p>By</p>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Event.City)
            </dd>
            <dt class="col-sm-2">
                @* @Html.DisplayNameFor(model => model.Event.DateTime) *@
                <p>Dato/Tid</p>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Event.DateTime)
            </dd>
        </dl>
        <div class="form-group button-container">
            <input type="submit" value="Slet" class="btn btn-danger large-btn" />
            <a asp-page="/Events/GetAllEvents" class="btn btn-secondary large-btn">Tilbage til event listen</a>
        </div>
    </form>    
</div> 

DCH/Pages/Events/GetAllEvents.cshtml
@page
@model DCH.Pages.Events.GetAllEventsModel
@{
    ViewData["Title"] = "GetAllEvents";
}
<h1>Administrer events</h1>

<div class="Create-btn">
    <a asp-page="CreateEvent" class="btn btn-primary">Opret ny event</a>
</div>

<div id="search">
        <form>
                <input type="text" asp-for="FilterCriteria" />
                <input type="submit" value="Søg" />

        </form>
    </div>

<table class="table">
    <thead>
        <tr>
            <th>
                Event Navn
            </th>
            <th>
                Beskrivelse
            </th>
            <th>
                By
            </th>
            <th>
                Dato og klokkeslæt
            </th>
            <th>
                Antal tilmeldte
            </th>
            <th>
                
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Events)
        {
            <tr>
                <td>
                    @item.Value.Name
                </td>
                <td>
                    @item.Value.Description
                </td>
                <td>
                    @item.Value.City
                </td>
                
                <td>
                    @item.Value.DateTime
                </td>
                <td>
                    @item.Value.ClickCount / @item.Value.MaxCount
                </td>
                <td>
                    <div class="button">
                        <p>
                            <a asp-page="UpdateEvent" asp-route-id="@item.Key" class="btn btn-secondary CRUD-btn">Opdater</a>
                        </p>
                        <p>
                            <a asp-page="DeleteEvent" asp-route-id="@item.Key" class="btn btn-danger CRUD-btn">Slet</a>
                        </p>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="back-btn">
    <a asp-page="/Login/Administration" class="btn btn-primary">Tilbage til administration</a>
</div>

DCH/Pages/Events/ReadOnlyEvents.cshtml
@page "{source?}"
@model DCH.Pages.Events.ReadOnlyEventsModel
@{
    ViewData["Title"] = "ReadOnlyEvents";
    var source = Model.Source ?? "NotActor"; 
}
<h1>Se alle events</h1>

<div id="search">
    <form>
        <input type="text" asp-for="FilterCriteria" />
        <input type="submit" value="Søg" />

    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Navn
            </th>
            <th>
                Beskrivelse
            </th>
            <th>
                By
            </th>
            <th>
                Dato/tid
            </th>
            <th>
                Antal tilmeldte
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Events)
        {
            <tr>
                <td>
                    @item.Value.Name
                </td>
                <td>
                    @item.Value.Description
                </td>
                <td>
                    @item.Value.City
                </td>
                <td>
                    @item.Value.DateTime
                </td>
                <td>
                    @item.Value.ClickCount / @item.Value.MaxCount
                </td>
                @if (source != "actor")
                {
                   
                }
                else
                {
                    <td>
                        <div class="button">
                            <p>
                                <form method="post" asp-page-handler="Register">
                                    <input type="hidden" name="eventId" value="@item.Key" />
                                    <button type="submit" class="btn btn-success same-width">Tilmeld</button>
                                </form>
                            </p>
                        
                            <p>
                                <form method="post" asp-page-handler="UndoRegister">
                                    <input type="hidden" name="eventId" value="@item.Key" />
                                    <button type="submit" class="btn btn-danger same-width">Afmeld</button>
                                </form>
                            </p>
                        
                        </div>                  
                    </td>                    
                }               
            </tr>
        }
    </tbody>
</table>
<div class="back-btn">
    @if (source == "actor")
    {
        <a asp-page="/Actors/Profile" asp-route-source="actor" class="btn btn-primary">Tilbage til din profil</a> 
    }
    else
    {
               
    }

</div>
<div class="bottom img">
    <img src="~/images/ag.jpg" width="300" height="200"/>
    <img src="~/images/lydighed.jpg" width="300" height="200" />
    <img src="~/images/rally.jpg" width="300" height="200" />
    <img src="~/images/puppy-training.jpg" width="300" height="200" />
</div>

DCH/Pages/Events/UpdateEvent.cshtml
@page
@model DCH.Pages.Events.UpdateEventModel
@{
    ViewData["Title"] = "Update Event";
}
<h1>Update Event</h1>
<form method="post">

    <div class="form-group">
        <label asp-for="@Model.Event.Id" class="control-label"></label>
        <input asp-for="@Model.Event.Id" class="form-control" readonly/>
        <span asp-validation-for="@Model.Event.Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.Name" class="control-label">Event navn (Må højst indholde 40 tegn)</label>
        <input asp-for="@Model.Event.Name" class="form-control"/>
        <span asp-validation-for="@Model.Event.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.Description" class="control-label">Beskrivelse (Må højst indholde 200 tegn)</label>
        <input asp-for="@Model.Event.Description" class="form-control" />
        <span asp-validation-for="@Model.Event.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.City" class="control-label">By (Må højst indholde 20 tegn)</label>
        <input asp-for="@Model.Event.City" class="form-control" />
        <span asp-validation-for="@Model.Event.City" class="text-danger"></span>
    </div>
    <div class="form-group">
    <label asp-for="@Model.Event.MaxCount" class="control-label">Maks antal deltagere</label>
    <input asp-for="@Model.Event.MaxCount" class="form-control" />
    <span asp-validation-for="@Model.Event.MaxCount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Event.DateTime" class="control-label">Dato og klokkeslæt</label>
        <input asp-for="@Model.Event.DateTime" class="form-control" />
        <span asp-validation-for="@Model.Event.DateTime" class="text-danger"></span>
    </div>
    <div class="form-group button-container">
        <input type="submit" value="Gem" class="btn btn-primary large-btn" />
        <a asp-page="/Events/GetAllEvents" class="btn btn-secondary large-btn">Tilbage til event listen</a>
    </div>
</form>
</div> 